[features]
seeds = false
[programs.devnet]
treasury = "artzp5sEtdxQrJhE27n4cxPzoTc1q5aMpxWneeAto9F"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/mnt/c/Users/34633/Documents/anchor-test/f/ARNP9nbSrYow8kTYxnDtn9mqUYmFuA3L8vb273MBu1XF.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
